### PR TITLE
Bubble Sort

### PR DESCRIPTION
**Pull request by monubucky**
This simply illustrates one of the famous sorting algorithm called bubble sort

### CODE REVIEW

**Comment by monubucky** [comment]
Please Acknowledge and Accept my pull request.

**Comment by divyanshugarg36** [comment]
Man this repo is for c programs and you sent a PR for python script 
Kindly update it asap else i will revert this PR in like 2 hours and mark it as invalid

**Comment by divyanshugarg36** [comment]
@monubucky :arrow_up:

**Comment by monubucky** [comment]
Sorry for this inconvenience, I have made bubble sort in both c and python,
so unfortunately I had upload python one but will change and upload
different algo.

Thank you for your time.

**Pull request merged**
